services:
  - type: web
    name: wordpress-woo
    env: docker
    repo: https://github.com/YOUR_USERNAME/wordpress-woo-render
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: standard
    envVars:
      - key: WORDPRESS_DB_HOST
        value: srv1578.hstgr.io      
      - key: WORDPRESS_DB_USER
        value: u674474931_wordpress_woo2            
      - key: WORDPRESS_DB_PASSWORD
        value: Wordpress-woo_@_2025             # Hostinger DB password
      - key: WORDPRESS_DB_NAME
        value: u674474931_wordpress_woo            # Hostinger DB name
